apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pyplanereport.fullname" . }}-cfg
  labels:
    {{- include "pyplanereport.labels" . | nindent 4 }}
data:
  PRJID: {{ .Values.planeso.projectid }}
  WSNAME: {{ .Values.planeso.workspacename }}
  APIKEY: {{ .Values.planeso.apikey }}
  TABLETITLE: {{ .Values.planeso.tabletitle }}
  IGNORESTATE: {{ .Values.planeso.ignorestate }}